#!/bin/bash
set -euo pipefail

echo "--- Searching for Clowns 🤡"
echo "$BUILDKITE_BUILD_CHECKOUT_PATH"

if grep -inr -C1 "🤡" . ; then
  echo "^^^ +++"
  echo "+++ :warning: Detected clowns! 🔪"

  echo "--- Removing Clowns 🤡"
  find . -type f -name '*.txt' -o -name '*.md' -o -name '*.sh' | while read -r file; do
    sed -i 's/🤡//g' "$file"
    echo "Removed clowns from $file"
  done

  echo "--- Clown removal complete."
  exit 1
else
  echo "No clowns detected."
  exit 0
fi